# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.14

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.14.1/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.14.1/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/ekaterinakuzina/Education/Практика/Encryption

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/ekaterinakuzina/Education/Практика/Encryption

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.14.1/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.14.1/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/ekaterinakuzina/Education/Практика/Encryption/CMakeFiles /Users/ekaterinakuzina/Education/Практика/Encryption/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/ekaterinakuzina/Education/Практика/Encryption/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named encryptions

# Build rule for target.
encryptions: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 encryptions
.PHONY : encryptions

# fast build rule for target.
encryptions/fast:
	$(MAKE) -f CMakeFiles/encryptions.dir/build.make CMakeFiles/encryptions.dir/build
.PHONY : encryptions/fast

Encoder.o: Encoder.cpp.o

.PHONY : Encoder.o

# target to build an object file
Encoder.cpp.o:
	$(MAKE) -f CMakeFiles/encryptions.dir/build.make CMakeFiles/encryptions.dir/Encoder.cpp.o
.PHONY : Encoder.cpp.o

Encoder.i: Encoder.cpp.i

.PHONY : Encoder.i

# target to preprocess a source file
Encoder.cpp.i:
	$(MAKE) -f CMakeFiles/encryptions.dir/build.make CMakeFiles/encryptions.dir/Encoder.cpp.i
.PHONY : Encoder.cpp.i

Encoder.s: Encoder.cpp.s

.PHONY : Encoder.s

# target to generate assembly for a file
Encoder.cpp.s:
	$(MAKE) -f CMakeFiles/encryptions.dir/build.make CMakeFiles/encryptions.dir/Encoder.cpp.s
.PHONY : Encoder.cpp.s

Encryptions-master/Encryptions/AES.o: Encryptions-master/Encryptions/AES.cpp.o

.PHONY : Encryptions-master/Encryptions/AES.o

# target to build an object file
Encryptions-master/Encryptions/AES.cpp.o:
	$(MAKE) -f CMakeFiles/encryptions.dir/build.make CMakeFiles/encryptions.dir/Encryptions-master/Encryptions/AES.cpp.o
.PHONY : Encryptions-master/Encryptions/AES.cpp.o

Encryptions-master/Encryptions/AES.i: Encryptions-master/Encryptions/AES.cpp.i

.PHONY : Encryptions-master/Encryptions/AES.i

# target to preprocess a source file
Encryptions-master/Encryptions/AES.cpp.i:
	$(MAKE) -f CMakeFiles/encryptions.dir/build.make CMakeFiles/encryptions.dir/Encryptions-master/Encryptions/AES.cpp.i
.PHONY : Encryptions-master/Encryptions/AES.cpp.i

Encryptions-master/Encryptions/AES.s: Encryptions-master/Encryptions/AES.cpp.s

.PHONY : Encryptions-master/Encryptions/AES.s

# target to generate assembly for a file
Encryptions-master/Encryptions/AES.cpp.s:
	$(MAKE) -f CMakeFiles/encryptions.dir/build.make CMakeFiles/encryptions.dir/Encryptions-master/Encryptions/AES.cpp.s
.PHONY : Encryptions-master/Encryptions/AES.cpp.s

Encryptions-master/Encryptions/SymAlg.o: Encryptions-master/Encryptions/SymAlg.cpp.o

.PHONY : Encryptions-master/Encryptions/SymAlg.o

# target to build an object file
Encryptions-master/Encryptions/SymAlg.cpp.o:
	$(MAKE) -f CMakeFiles/encryptions.dir/build.make CMakeFiles/encryptions.dir/Encryptions-master/Encryptions/SymAlg.cpp.o
.PHONY : Encryptions-master/Encryptions/SymAlg.cpp.o

Encryptions-master/Encryptions/SymAlg.i: Encryptions-master/Encryptions/SymAlg.cpp.i

.PHONY : Encryptions-master/Encryptions/SymAlg.i

# target to preprocess a source file
Encryptions-master/Encryptions/SymAlg.cpp.i:
	$(MAKE) -f CMakeFiles/encryptions.dir/build.make CMakeFiles/encryptions.dir/Encryptions-master/Encryptions/SymAlg.cpp.i
.PHONY : Encryptions-master/Encryptions/SymAlg.cpp.i

Encryptions-master/Encryptions/SymAlg.s: Encryptions-master/Encryptions/SymAlg.cpp.s

.PHONY : Encryptions-master/Encryptions/SymAlg.s

# target to generate assembly for a file
Encryptions-master/Encryptions/SymAlg.cpp.s:
	$(MAKE) -f CMakeFiles/encryptions.dir/build.make CMakeFiles/encryptions.dir/Encryptions-master/Encryptions/SymAlg.cpp.s
.PHONY : Encryptions-master/Encryptions/SymAlg.cpp.s

Encryptions-master/common/includes.o: Encryptions-master/common/includes.cpp.o

.PHONY : Encryptions-master/common/includes.o

# target to build an object file
Encryptions-master/common/includes.cpp.o:
	$(MAKE) -f CMakeFiles/encryptions.dir/build.make CMakeFiles/encryptions.dir/Encryptions-master/common/includes.cpp.o
.PHONY : Encryptions-master/common/includes.cpp.o

Encryptions-master/common/includes.i: Encryptions-master/common/includes.cpp.i

.PHONY : Encryptions-master/common/includes.i

# target to preprocess a source file
Encryptions-master/common/includes.cpp.i:
	$(MAKE) -f CMakeFiles/encryptions.dir/build.make CMakeFiles/encryptions.dir/Encryptions-master/common/includes.cpp.i
.PHONY : Encryptions-master/common/includes.cpp.i

Encryptions-master/common/includes.s: Encryptions-master/common/includes.cpp.s

.PHONY : Encryptions-master/common/includes.s

# target to generate assembly for a file
Encryptions-master/common/includes.cpp.s:
	$(MAKE) -f CMakeFiles/encryptions.dir/build.make CMakeFiles/encryptions.dir/Encryptions-master/common/includes.cpp.s
.PHONY : Encryptions-master/common/includes.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/encryptions.dir/build.make CMakeFiles/encryptions.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/encryptions.dir/build.make CMakeFiles/encryptions.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/encryptions.dir/build.make CMakeFiles/encryptions.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... encryptions"
	@echo "... Encoder.o"
	@echo "... Encoder.i"
	@echo "... Encoder.s"
	@echo "... Encryptions-master/Encryptions/AES.o"
	@echo "... Encryptions-master/Encryptions/AES.i"
	@echo "... Encryptions-master/Encryptions/AES.s"
	@echo "... Encryptions-master/Encryptions/SymAlg.o"
	@echo "... Encryptions-master/Encryptions/SymAlg.i"
	@echo "... Encryptions-master/Encryptions/SymAlg.s"
	@echo "... Encryptions-master/common/includes.o"
	@echo "... Encryptions-master/common/includes.i"
	@echo "... Encryptions-master/common/includes.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

